import Nav, { Footer } from "@/components/Nav";

export default function TermsPage() {
  return (
    <>
      <Nav />
      <main className="shell" style={{ maxWidth: 720, paddingTop: "clamp(48px,6vw,80px)", paddingBottom: 96 }}>
        <div className="kicker" style={{ marginBottom: 16 }}>Legal</div>
        <h1 className="display" style={{ fontSize: "clamp(32px,5vw,64px)", marginBottom: 8 }}>Terms of Use</h1>
        <p className="font-mono" style={{ fontSize: 12, color: "#7A7A88", marginBottom: 48, letterSpacing: "0.06em" }}>
          Effective: June 2025 · Last updated: June 2025
        </p>

        <div style={{ color: "#C4C4CC", fontSize: 15, lineHeight: 1.85 }}>

          <Section title="1. Acceptance of Terms">
            <p>By accessing or using Conciply ("the Service", "we", "us"), you ("User") agree to be legally bound by these Terms of Use ("Terms"). If you do not agree to all of these Terms, you must not use the Service. Your continued use of the Service constitutes ongoing acceptance of these Terms as updated from time to time.</p>
          </Section>

          <Section title="2. Eligibility">
            <p>You must be at least 18 years of age to use this Service. By using Conciply, you represent and warrant that you are 18 or older and have the legal capacity to enter into a binding agreement. If you are using the Service on behalf of a business, you represent that you have authority to bind that business to these Terms.</p>
          </Section>

          <Section title="3. Nature of the Service — AI Output Is Not Professional Advice">
            <p style={{ color: "#F4F4F1", fontWeight: 600 }}>IMPORTANT: The content generated by Conciply is produced by artificial intelligence and is provided for informational and inspirational purposes only. It does not constitute — and must not be treated as — professional business, financial, legal, tax, investment, marketing, or any other form of regulated professional advice.</p>
            <p style={{ marginTop: 12 }}>AI-generated output may be inaccurate, incomplete, outdated, misleading, or entirely inapplicable to your specific situation. Conciply makes no representations or warranties regarding the accuracy, reliability, or fitness of any generated content.</p>
            <p style={{ marginTop: 12 }}>You agree that:</p>
            <ul style={{ paddingLeft: 20, marginTop: 8 }}>
              <li style={{ marginBottom: 6 }}>You will independently verify all AI-generated recommendations before acting on them.</li>
              <li style={{ marginBottom: 6 }}>You will consult qualified professionals (lawyers, accountants, financial advisors, etc.) before making significant business decisions.</li>
              <li style={{ marginBottom: 6 }}>You bear full responsibility for any decisions made based on content generated by Conciply.</li>
              <li style={{ marginBottom: 6 }}>Conciply is not liable for any losses, damages, or negative outcomes resulting from your use of or reliance on AI-generated content.</li>
            </ul>
          </Section>

          <Section title="4. Subscriptions and Billing">
            <p>Paid plans are billed on a monthly recurring basis via Stripe. By subscribing, you authorize Conciply to charge your payment method each month until you cancel.</p>
            <ul style={{ paddingLeft: 20, marginTop: 8 }}>
              <li style={{ marginBottom: 6 }}>Subscriptions renew automatically at the end of each billing cycle.</li>
              <li style={{ marginBottom: 6 }}>You may cancel at any time. Cancellation takes effect at the end of the current billing period — access continues until then.</li>
              <li style={{ marginBottom: 6 }}>No partial refunds are issued for unused time within a billing period.</li>
              <li style={{ marginBottom: 6 }}>Refunds may be granted at our sole discretion for verified technical failures on our part. Requests must be submitted to hello@conciply.com within 7 days of the charge.</li>
              <li style={{ marginBottom: 6 }}>We reserve the right to change pricing with 30 days' notice. Continued use after a price change constitutes acceptance of the new price.</li>
            </ul>
          </Section>

          <Section title="5. License Keys and Access">
            <p>Upon subscribing, you receive a license key that unlocks your plan features. License keys are:</p>
            <ul style={{ paddingLeft: 20, marginTop: 8 }}>
              <li style={{ marginBottom: 6 }}>For your personal or team use only — not for resale, sublicensing, or redistribution.</li>
              <li style={{ marginBottom: 6 }}>Tied to your active subscription. Access terminates when your subscription lapses.</li>
              <li style={{ marginBottom: 6 }}>Your responsibility to keep secure. Do not share your key publicly. You are liable for all usage under your key.</li>
            </ul>
            <p style={{ marginTop: 12 }}>Agency plan subscribers may use the Service to generate reports for clients. All other plans are for personal or internal business use only.</p>
          </Section>

          <Section title="6. Acceptable Use">
            <p>You agree not to use Conciply to:</p>
            <ul style={{ paddingLeft: 20, marginTop: 8 }}>
              <li style={{ marginBottom: 6 }}>Submit confidential, personally identifiable, or sensitive third-party information.</li>
              <li style={{ marginBottom: 6 }}>Generate content intended to deceive, defraud, or harm others.</li>
              <li style={{ marginBottom: 6 }}>Attempt to reverse-engineer, scrape, or systematically abuse the API or platform.</li>
              <li style={{ marginBottom: 6 }}>Circumvent rate limits, paywalls, or access controls by any means.</li>
              <li style={{ marginBottom: 6 }}>Resell, white-label, or repackage the Service or its output as your own product without written permission.</li>
              <li style={{ marginBottom: 6 }}>Use the Service for any unlawful purpose or in violation of any applicable laws.</li>
            </ul>
            <p style={{ marginTop: 12 }}>We reserve the right to suspend or terminate access immediately and without notice for violations of this section.</p>
          </Section>

          <Section title="7. Intellectual Property">
            <p>The growth reports and playbooks generated using your inputs are yours to use for personal, internal business, or (for Agency subscribers) client purposes.</p>
            <p style={{ marginTop: 12 }}>Conciply retains all rights, title, and interest in and to the platform, design, codebase, AI prompting system, and brand. Nothing in these Terms transfers any ownership of Conciply's intellectual property to you.</p>
          </Section>

          <Section title="8. Disclaimer of Warranties">
            <p style={{ textTransform: "uppercase", fontSize: 13, letterSpacing: "0.03em" }}>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.</p>
          </Section>

          <Section title="9. Limitation of Liability">
            <p style={{ textTransform: "uppercase", fontSize: 13, letterSpacing: "0.03em" }}>TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, CONCIPLY, ITS OWNERS, EMPLOYEES, AND AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES — INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, REVENUE, DATA, GOODWILL, BUSINESS OPPORTUNITIES, OR BUSINESS INTERRUPTION — ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
            <p style={{ marginTop: 12, textTransform: "uppercase", fontSize: 13, letterSpacing: "0.03em" }}>IN NO EVENT SHALL OUR TOTAL AGGREGATE LIABILITY TO YOU FOR ANY CLAIMS ARISING FROM OR RELATING TO THESE TERMS OR THE SERVICE EXCEED THE TOTAL AMOUNT YOU PAID TO CONCIPLY IN THE THREE (3) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR $50 USD, WHICHEVER IS GREATER.</p>
          </Section>

          <Section title="10. Indemnification">
            <p>You agree to indemnify, defend, and hold harmless Conciply and its owners, officers, employees, and affiliates from and against any claims, liabilities, damages, losses, costs, and expenses (including reasonable legal fees) arising out of or relating to: (a) your use of the Service; (b) your violation of these Terms; (c) your violation of any third-party rights; or (d) any content you submit to the Service.</p>
          </Section>

          <Section title="11. Dispute Resolution and Governing Law">
            <p>These Terms are governed by and construed in accordance with the laws of the jurisdiction in which Conciply operates, without regard to conflict of law principles.</p>
            <p style={{ marginTop: 12 }}>Any dispute arising out of or relating to these Terms or the Service shall first be attempted to be resolved through good-faith negotiation. If unresolved within 30 days, disputes shall be submitted to binding arbitration on an individual basis. <strong style={{ color: "#F4F4F1" }}>You waive any right to participate in a class action lawsuit or class-wide arbitration against Conciply.</strong></p>
          </Section>

          <Section title="12. Termination">
            <p>We reserve the right to suspend or terminate your access to the Service at any time, with or without notice, for any violation of these Terms or for any other reason at our sole discretion. Upon termination, your license key will be deactivated. No refund will be issued for the remaining subscription period if termination is due to a Terms violation.</p>
          </Section>

          <Section title="13. Severability">
            <p>If any provision of these Terms is found to be unenforceable or invalid by a court of competent jurisdiction, that provision shall be limited or eliminated to the minimum extent necessary so that the remaining Terms remain in full force and effect.</p>
          </Section>

          <Section title="14. Changes to These Terms">
            <p>We may update these Terms at any time by posting the revised version on this page with an updated date. For material changes, we will make reasonable efforts to notify users. Continued use of the Service after changes constitutes acceptance of the revised Terms.</p>
          </Section>

          <Section title="15. Contact">
            <p>Questions about these Terms? Email us at <a href="mailto:hello@conciply.com" style={{ color: "var(--n1)", textDecoration: "underline" }}>hello@conciply.com</a>.</p>
          </Section>

        </div>
      </main>
      <Footer />
    </>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 40 }}>
      <h2 className="font-mono" style={{ fontSize: 13, fontWeight: 700, letterSpacing: "0.1em",
                                          textTransform: "uppercase", color: "#F4F4F1", marginBottom: 12 }}>
        {title}
      </h2>
      {children}
    </div>
  );
}
