"use client";
import { useEffect, useState, Suspense } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Nav, { Footer } from "@/components/Nav";
import SectionCard from "@/components/SectionCard";
import AssetGenerator from "@/components/AssetGenerator";
import { getReport, getLicensePlan, getLicenseKey, updateReportSection } from "@/lib/workspace";
import { SECTION_LABELS, FREE_SECTIONS } from "@/lib/types";
import type { StoredReport, SectionKey, GrowthReport } from "@/lib/types";

// ── Shared sidebar config (mirrors ReportView) ────────────────────────────────
const GROUPS: { label: string; color: string; keys: SectionKey[] }[] = [
  { label:"Analysis",  color:"var(--n1)", keys:["executiveSummary","marketAnalysis","competitorAnalysis","positioning"] },
  { label:"Growth",    color:"var(--n3)", keys:["growthOpportunities","acquisitionPlan","funnelImprovements"] },
  { label:"Assets",    color:"var(--n2)", keys:["marketingAssets","salesAssets","retentionStrategy","socialMediaStrategy"] },
  { label:"Execution", color:"#9A9AA8",  keys:["kpiDashboard","topRoiActions","plan7Day","plan30Day","plan90Day","immediateActions"] },
];
const ALL_KEYS: SectionKey[] = GROUPS.flatMap(g => g.keys);
const sectionNum = (key: SectionKey) => String(ALL_KEYS.indexOf(key) + 1).padStart(2, "0");

const ICONS: Record<SectionKey, string> = {
  executiveSummary:"◈", marketAnalysis:"◎", competitorAnalysis:"⊕", positioning:"◆",
  growthOpportunities:"▲", acquisitionPlan:"➤", funnelImprovements:"◑",
  marketingAssets:"✦", salesAssets:"◉", retentionStrategy:"⟳", socialMediaStrategy:"◈",
  kpiDashboard:"▣", topRoiActions:"★", plan7Day:"①", plan30Day:"②", plan90Day:"③", immediateActions:"⚡",
};

const SECTION_SUBTITLES: Partial<Record<SectionKey, string>> = {
  executiveSummary:    "Your ICP, unique value proposition, and single biggest opportunity at a glance.",
  marketAnalysis:      "TAM / SAM / SOM sizing and the market trends that matter most for your growth.",
  competitorAnalysis:  "Who you're up against, where they're weak, and the gaps you can exploit.",
  positioning:         "How to frame your brand so the right customers immediately get it.",
  growthOpportunities: "Organic, paid, product-led, and viral levers ranked by potential impact.",
  acquisitionPlan:     "Which channels to prioritise, exact tactics, and how to split your budget.",
  funnelImprovements:  "Where you're leaking revenue and how to fix each stage of the funnel.",
  marketingAssets:     "Ready-to-use landing copy, ad headlines, and a full email sequence.",
  salesAssets:         "Cold outreach script, discovery questions, and objection-handling playbook.",
  retentionStrategy:   "Onboarding steps, engagement loops, and upsell moments to reduce churn.",
  socialMediaStrategy: "Platform-by-platform playbooks, post ideas, hooks, and a 4-week content calendar.",
  kpiDashboard:        "The metrics you must track, your 90-day targets, and red flags to watch.",
  topRoiActions:       "Your highest-leverage moves ranked by impact, speed, and ease — do these first.",
  plan7Day:            "Day-by-day sprint to get the most critical foundations in place this week.",
  plan30Day:           "Week-by-week execution plan to build momentum and hit your first milestone.",
  plan90Day:           "Three-month roadmap from launch to traction — themes, milestones, and metrics.",
  immediateActions:    "What to do in the next 24 and 72 hours to start moving right now.",
};

// ── Plain-text export helper ──────────────────────────────────────────────────
function formatReportAsText(stored: StoredReport): string {
  const r = stored.report as unknown as Record<string, unknown>;
  const lines: string[] = [];
  const hr = "─".repeat(60);
  lines.push(`GROWTH PLAYBOOK: ${stored.input.toUpperCase()}`);
  lines.push(`Generated by Conciply · ${new Date(stored.createdAt).toLocaleDateString()}`);
  lines.push(hr);
  const list = (arr: unknown[]) => arr.map(s => `  • ${s}`).join("\n");
  for (const key of ALL_KEYS) {
    const section = r[key];
    if (!section) continue;
    lines.push(`\n${SECTION_LABELS[key as SectionKey].toUpperCase()}`);
    lines.push(hr);
    if (key === "executiveSummary") {
      const s = section as GrowthReport["executiveSummary"];
      lines.push(`ICP: ${s.icp}\nUVP: ${s.uvp}\nTop Opportunity: ${s.topOpportunity}`);
      if (s.assumptions?.length) lines.push(`Assumptions:\n${list(s.assumptions)}`);
    } else if (key === "topRoiActions") {
      const s = section as GrowthReport["topRoiActions"];
      s.actions?.forEach((a, i) => lines.push(`  ${i+1}. ${a.title} (Score: ${a.score})\n     ${a.description}`));
    } else {
      lines.push(JSON.stringify(section, null, 2));
    }
  }
  lines.push(`\n${hr}\nPowered by Conciply · conciply.com`);
  return lines.join("\n");
}

// ── Main workspace component ──────────────────────────────────────────────────
function WorkspaceContent() {
  const router = useRouter();
  const params = useSearchParams();
  const id = params.get("id") ?? "";

  const [stored, setStored]           = useState<StoredReport | null>(null);
  const [tier, setTier]               = useState<string | null>(null);
  const [active, setActive]           = useState<SectionKey>("executiveSummary");
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [deepDiveKey, setDeepDiveKey] = useState<SectionKey | null>(null);
  const [regenLoading, setRegenLoading] = useState<SectionKey | null>(null);
  const [copied, setCopied]           = useState(false);
  const [billingLoading, setBillingLoading] = useState(false);

  useEffect(() => {
    const plan = getLicensePlan();
    if (!plan) { router.push("/unlock"); return; }
    const r = getReport(id);
    if (!r) { router.push("/"); return; }
    setStored(r);
    setTier(plan);
  }, [id, router]);

  const handleRegenerate = async (key: SectionKey) => {
    if (!stored) return;
    setRegenLoading(key);
    try {
      const licenseKey = getLicenseKey();
      const sectionData = JSON.stringify((stored.report as unknown as Record<string, unknown>)[key] ?? {});
      const res = await fetch("/api/refine", {
        method: "POST",
        headers: { "Content-Type": "application/json", ...(licenseKey ? { "x-conciply-license": licenseKey } : {}) },
        body: JSON.stringify({ sectionKey: key, input: stored.input, currentContent: sectionData }),
      });
      const data = await res.json();
      if (res.ok && data.section) {
        updateReportSection(stored.id, key, data.section as GrowthReport[typeof key]);
        setStored(getReport(stored.id));
      }
    } finally {
      setRegenLoading(null);
    }
  };

  const handleCopy = () => {
    if (!stored) return;
    navigator.clipboard.writeText(formatReportAsText(stored)).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleBilling = async () => {
    setBillingLoading(true);
    try {
      const key = getLicenseKey();
      const res = await fetch("/api/billing-portal", {
        method: "POST",
        headers: { ...(key ? { "x-conciply-license": key } : {}) },
      });
      const data = await res.json();
      if (data.url) window.location.href = data.url;
      else alert(data.error || "Could not open billing portal.");
    } finally {
      setBillingLoading(false);
    }
  };

  if (!stored) return null;

  const isPro     = tier === "pro" || tier === "agency";
  const activeGroup = GROUPS.find(g => g.keys.includes(active))!;

  return (
    <>
      <div style={{ display:"flex", minHeight:"calc(100vh - 64px)", position:"relative" }}>

        {/* Mobile toggle */}
        <button onClick={() => setSidebarOpen(o => !o)} className="font-mono"
          style={{ display:"none", position:"fixed", bottom:24, right:24, zIndex:50,
                   background:"var(--n2)", color:"#000", border:"none", padding:"12px 18px",
                   fontSize:12, letterSpacing:"0.1em", cursor:"pointer" }}
          data-ws-toggle>
          {sidebarOpen ? "✕ Close" : "☰ Sections"}
        </button>

        {/* ── Left sidebar ──────────────────────────────────────────────── */}
        <aside style={{
          width:260, flexShrink:0, borderRight:"2px solid #1E1E22",
          position:"sticky", top:64, height:"calc(100vh - 64px)",
          overflow:"hidden", display:"flex", flexDirection:"column",
          background:"#0A0A0B",
        }}>
          {/* Report title + tier badge */}
          <div style={{ padding:"20px 16px 16px", borderBottom:"1px solid #1E1E22" }}>
            <div style={{ fontSize:10, fontFamily:"var(--font-mono)", letterSpacing:"0.12em",
                          color:"#5C5C63", textTransform:"uppercase", marginBottom:6 }}>
              Workspace
            </div>
            <div style={{ fontSize:13, fontWeight:700, color:"#F4F4F1", lineHeight:1.4,
                          display:"-webkit-box", WebkitLineClamp:2, WebkitBoxOrient:"vertical",
                          overflow:"hidden", marginBottom:10 }}>
              {stored.input}
            </div>
            <span style={{ fontSize:10, fontFamily:"var(--font-mono)", fontWeight:700,
                           letterSpacing:"0.1em", textTransform:"uppercase",
                           color:"#000", background:"var(--n2)", padding:"3px 8px" }}>
              {tier} · editing
            </span>
          </div>

          {/* Section nav — only this scrolls, footer stays pinned */}
          <nav style={{ flex:1, overflowY:"auto", padding:"8px 0" }}>
            {GROUPS.map(group => (
              <div key={group.label} style={{ marginBottom:4 }}>
                <div style={{ padding:"10px 16px 6px", fontSize:9, fontFamily:"var(--font-mono)",
                              fontWeight:700, letterSpacing:"0.14em", textTransform:"uppercase",
                              color: group.color }}>
                  {group.label}
                </div>
                {group.keys.map(key => {
                  const isActive = key === active;
                  return (
                    <button key={key} onClick={() => { setActive(key); setSidebarOpen(false); }}
                      style={{ width:"100%", textAlign:"left", border:"none", cursor:"pointer",
                               padding:"9px 16px", display:"flex", alignItems:"center", gap:10,
                               background: isActive ? "#16161A" : "transparent",
                               borderLeft: isActive ? `2px solid ${group.color}` : "2px solid transparent",
                               transition:"background 0.1s" }}>
                      <span style={{ fontSize:9, fontFamily:"var(--font-mono)",
                                     color: isActive ? group.color : "#3C3C42", flexShrink:0, width:18 }}>
                        {sectionNum(key)}
                      </span>
                      <span style={{ fontSize:13, color: isActive ? group.color : "#5C5C63", flexShrink:0 }}>
                        {ICONS[key]}
                      </span>
                      <span style={{ fontSize:12, fontFamily:"var(--font-mono)", letterSpacing:"0.04em",
                                     color: isActive ? "#F4F4F1" : "#9A9AA8", lineHeight:1.3 }}>
                        {SECTION_LABELS[key]}
                      </span>
                      {regenLoading === key && (
                        <span style={{ marginLeft:"auto", fontSize:10, color:"var(--n1)",
                                       fontFamily:"var(--font-mono)", animation:"pulse 1s infinite" }}>
                          ↻
                        </span>
                      )}
                    </button>
                  );
                })}
              </div>
            ))}
          </nav>

          {/* Sidebar footer actions */}
          <div style={{ padding:"12px 16px", borderTop:"1px solid #1E1E22", display:"flex", flexDirection:"column", gap:6 }}>
            <a href={`/report?id=${stored.id}`} className="btn-ghost"
              style={{ padding:"8px 12px", fontSize:11, textAlign:"center", letterSpacing:"0.08em" }}>
              ← View Report
            </a>
            <button onClick={handleCopy} className="btn-ghost"
              style={{ padding:"8px 12px", fontSize:11, letterSpacing:"0.08em",
                       color: copied ? "var(--n3)" : undefined,
                       borderColor: copied ? "var(--n3)" : undefined }}>
              {copied ? "✓ Copied!" : "Copy Full Report"}
            </button>
            <button onClick={() => window.print()} className="btn-ghost"
              style={{ padding:"8px 12px", fontSize:11, letterSpacing:"0.08em" }}>
              Print / PDF
            </button>
            <button onClick={handleBilling} disabled={billingLoading} className="btn-ghost"
              style={{ padding:"8px 12px", fontSize:11, letterSpacing:"0.08em" }}>
              {billingLoading ? "Opening…" : "Manage Billing"}
            </button>
            <a href="/" className="btn-neon"
              style={{ padding:"8px 12px", fontSize:11, textAlign:"center", letterSpacing:"0.08em" }}>
              + New Report
            </a>
          </div>
        </aside>

        {/* ── Right content panel ──────────────────────────────────────── */}
        <main style={{ flex:1, minWidth:0, display:"flex", flexDirection:"column" }}>

          {/* Sticky breadcrumb + regen/deep-dive actions */}
          <div style={{ position:"sticky", top:64, zIndex:20,
                        background:"rgba(10,10,11,0.95)", backdropFilter:"blur(8px)",
                        borderBottom:"1px solid #1E1E22", padding:"14px 32px",
                        display:"flex", alignItems:"center", justifyContent:"space-between", gap:16 }}>
            <div style={{ display:"flex", alignItems:"center", gap:12 }}>
              <span style={{ fontSize:10, fontFamily:"var(--font-mono)", color: activeGroup.color,
                             letterSpacing:"0.12em", textTransform:"uppercase" }}>
                {activeGroup.label}
              </span>
              <span style={{ color:"#2A2A2E" }}>›</span>
              <span style={{ fontSize:12, fontFamily:"var(--font-mono)", color:"#F4F4F1",
                             letterSpacing:"0.06em" }}>
                {SECTION_LABELS[active]}
              </span>
            </div>
            <div style={{ display:"flex", gap:6, alignItems:"center" }}>
              <span style={{ fontSize:10, fontFamily:"var(--font-mono)", color:"#5C5C63",
                             letterSpacing:"0.1em" }}>
                {sectionNum(active)} / {ALL_KEYS.length}
              </span>
              <button onClick={() => handleRegenerate(active)}
                disabled={regenLoading !== null} className="btn-ghost"
                style={{ padding:"6px 12px", fontSize:11, letterSpacing:"0.06em",
                         color:"var(--n1)", borderColor:"var(--n1)",
                         opacity: regenLoading ? 0.5 : 1 }}>
                {regenLoading === active ? "↻ Regenerating…" : "↻ Regen"}
              </button>
              {isPro && (
                <button onClick={() => setDeepDiveKey(active)} className="btn-ghost"
                  style={{ padding:"6px 12px", fontSize:11, letterSpacing:"0.06em",
                           color:"var(--n2)", borderColor:"var(--n2)" }}>
                  ⚡ Deep Dive
                </button>
              )}
            </div>
          </div>

          {/* Section content */}
          <div style={{ padding:"32px 40px", flex:1 }}>

            {/* Big section title */}
            <div style={{ marginBottom:32, paddingBottom:24, borderBottom:`2px solid ${activeGroup.color}` }}>
              <div style={{ fontSize:11, fontFamily:"var(--font-mono)", letterSpacing:"0.14em",
                            textTransform:"uppercase", color: activeGroup.color, marginBottom:10 }}>
                {sectionNum(active)} — {activeGroup.label}
              </div>
              <h2 className="display" style={{ fontSize:"clamp(32px, 3.5vw, 56px)",
                                               fontWeight:900, color:"#F4F4F1", lineHeight:1.05,
                                               margin:0, letterSpacing:"-0.02em" }}>
                {SECTION_LABELS[active]}
              </h2>
              {SECTION_SUBTITLES[active] && (
                <p style={{ margin:"12px 0 0", fontSize:13, color:"#9A9AA8",
                            lineHeight:1.5, fontFamily:"var(--font-grotesk), sans-serif" }}>
                  {SECTION_SUBTITLES[active]}
                </p>
              )}
            </div>

            {regenLoading === active ? (
              <div style={{ padding:"32px 0" }}>
                <div className="skel" style={{ height:12, width:"40%", marginBottom:12 }} />
                <div className="skel" style={{ height:12, width:"65%", marginBottom:8 }} />
                <div className="skel" style={{ height:12, width:"50%" }} />
                <div className="kicker" style={{ marginTop:20, color:"var(--n1)" }}>Regenerating section…</div>
              </div>
            ) : (
              <SectionCard
                sectionKey={active}
                report={stored.report}
                locked={false}
              />
            )}

            {/* Prev / Next navigation */}
            <div style={{ display:"flex", justifyContent:"space-between", marginTop:40, gap:12 }}>
              {(() => {
                const idx  = ALL_KEYS.indexOf(active);
                const prev = idx > 0 ? ALL_KEYS[idx - 1] : null;
                const next = idx < ALL_KEYS.length - 1 ? ALL_KEYS[idx + 1] : null;
                return (
                  <>
                    <button onClick={() => prev && setActive(prev)} disabled={!prev}
                      className="btn-ghost" style={{ padding:"10px 18px", fontSize:12,
                      opacity: prev ? 1 : 0.2, cursor: prev ? "pointer" : "default" }}>
                      ← {prev ? SECTION_LABELS[prev] : ""}
                    </button>
                    <button onClick={() => next && setActive(next)} disabled={!next}
                      className="btn-ghost" style={{ padding:"10px 18px", fontSize:12,
                      opacity: next ? 1 : 0.2, cursor: next ? "pointer" : "default",
                      borderColor: next ? activeGroup.color : undefined,
                      color: next ? activeGroup.color : undefined }}>
                      {next ? SECTION_LABELS[next] : ""} →
                    </button>
                  </>
                );
              })()}
            </div>
          </div>
        </main>

        <style>{`
          @media (max-width: 768px) {
            [data-ws-toggle] { display: block !important; }
          }
        `}</style>
      </div>

      {deepDiveKey && stored && (
        <AssetGenerator
          sectionKey={deepDiveKey}
          input={stored.input}
          report={stored.report}
          onClose={() => setDeepDiveKey(null)}
        />
      )}
    </>
  );
}

export default function WorkspacePage() {
  return (
    <>
      <Nav />
      <Suspense>
        <WorkspaceContent />
      </Suspense>
      <Footer />
    </>
  );
}
