"use client";
import { useEffect, useState, Suspense } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Nav, { Footer } from "@/components/Nav";
import SectionCard from "@/components/SectionCard";
import AssetGenerator from "@/components/AssetGenerator";
import { getReport, getLicensePlan, getLicenseKey, updateReportSection } from "@/lib/workspace";
import { SECTION_ORDER, SECTION_LABELS } from "@/lib/types";
import type { StoredReport, SectionKey, GrowthReport } from "@/lib/types";

function formatReportAsText(stored: StoredReport): string {
  const r = stored.report as unknown as Record<string, unknown>;
  const lines: string[] = [];
  const hr = "─".repeat(60);

  lines.push(`GROWTH PLAYBOOK: ${stored.input.toUpperCase()}`);
  lines.push(`Generated by Conciply · ${new Date(stored.createdAt).toLocaleDateString()}`);
  lines.push(hr);

  const list = (arr: unknown[]) => arr.map(s => `  • ${s}`).join("\n");

  for (const key of SECTION_ORDER) {
    const section = r[key];
    if (!section) continue;
    lines.push(`\n${SECTION_LABELS[key as SectionKey].toUpperCase()}`);
    lines.push(hr);

    if (key === "executiveSummary") {
      const s = section as GrowthReport["executiveSummary"];
      lines.push(`ICP: ${s.icp}`);
      lines.push(`UVP: ${s.uvp}`);
      lines.push(`Top Opportunity: ${s.topOpportunity}`);
      if (s.assumptions?.length) lines.push(`Assumptions:\n${list(s.assumptions)}`);
    } else if (key === "marketAnalysis") {
      const s = section as GrowthReport["marketAnalysis"];
      lines.push(`TAM: ${s.tam}\nSAM: ${s.sam}\nSOM: ${s.som}`);
      if (s.trends?.length) lines.push(`Trends:\n${list(s.trends)}`);
    } else if (key === "competitorAnalysis") {
      const s = section as GrowthReport["competitorAnalysis"];
      s.competitors?.forEach(c => lines.push(`  ${c.name}\n    Strength: ${c.strength}\n    Weakness: ${c.weakness}`));
      if (s.gaps?.length) lines.push(`Gaps:\n${list(s.gaps)}`);
      if (s.advantages?.length) lines.push(`Advantages:\n${list(s.advantages)}`);
    } else if (key === "positioning") {
      const s = section as GrowthReport["positioning"];
      lines.push(`UVP: ${s.uvp}\nMessaging: ${s.messaging}\n${s.brandNarrative}`);
    } else if (key === "growthOpportunities") {
      const s = section as GrowthReport["growthOpportunities"];
      if (s.organic?.length) lines.push(`Organic:\n${list(s.organic)}`);
      if (s.paid?.length) lines.push(`Paid:\n${list(s.paid)}`);
      if (s.plg?.length) lines.push(`Product-Led Growth:\n${list(s.plg)}`);
      if (s.viral?.length) lines.push(`Viral:\n${list(s.viral)}`);
    } else if (key === "acquisitionPlan") {
      const s = section as GrowthReport["acquisitionPlan"];
      s.channels?.forEach(c => lines.push(`  ${c.name} [${c.priority}]: ${c.rationale}`));
      if (s.tactics?.length) lines.push(`Tactics:\n${list(s.tactics)}`);
      lines.push(`Budget: ${s.budgetGuidance}`);
    } else if (key === "funnelImprovements") {
      const s = section as GrowthReport["funnelImprovements"];
      if (s.awareness?.length) lines.push(`Awareness:\n${list(s.awareness)}`);
      if (s.activation?.length) lines.push(`Activation:\n${list(s.activation)}`);
      if (s.retention?.length) lines.push(`Retention:\n${list(s.retention)}`);
      if (s.referral?.length) lines.push(`Referral:\n${list(s.referral)}`);
    } else if (key === "marketingAssets") {
      const s = section as GrowthReport["marketingAssets"];
      lines.push(`Landing Copy:\n${s.landingCopy}`);
      if (s.adCopy?.length) lines.push(`Ad Headlines:\n${list(s.adCopy)}`);
      s.emailSequence?.forEach((e, i) => lines.push(`Email ${i+1}: ${e.subject}\n${e.body}\nCTA: ${e.cta}`));
    } else if (key === "salesAssets") {
      const s = section as GrowthReport["salesAssets"];
      lines.push(`Outreach Script:\n${s.outreachScript}`);
      if (s.discoveryQuestions?.length) lines.push(`Discovery Questions:\n${list(s.discoveryQuestions)}`);
      s.objections?.forEach(o => lines.push(`  Q: ${o.objection}\n  A: ${o.response}`));
    } else if (key === "retentionStrategy") {
      const s = section as GrowthReport["retentionStrategy"];
      if (s.onboarding?.length) lines.push(`Onboarding:\n${list(s.onboarding)}`);
      if (s.engagementLoops?.length) lines.push(`Engagement Loops:\n${list(s.engagementLoops)}`);
      if (s.upsells?.length) lines.push(`Upsells:\n${list(s.upsells)}`);
    } else if (key === "kpiDashboard") {
      const s = section as GrowthReport["kpiDashboard"];
      s.metrics?.forEach(m => lines.push(`  ${m.metric}: ${m.target} (${m.frequency})`));
      if (s.targets?.length) lines.push(`90-Day Targets:\n${list(s.targets)}`);
      if (s.warnings?.length) lines.push(`Red Flags:\n${list(s.warnings)}`);
    } else if (key === "topRoiActions") {
      const s = section as GrowthReport["topRoiActions"];
      s.actions?.forEach((a, i) => lines.push(`  ${i+1}. ${a.title} (Score: ${a.score})\n     ${a.description}`));
    } else if (key === "plan7Day") {
      const s = section as GrowthReport["plan7Day"];
      s.days?.forEach(d => lines.push(`  Day ${d.day}:\n${list(d.tasks)}`));
    } else if (key === "plan30Day") {
      const s = section as GrowthReport["plan30Day"];
      s.weeks?.forEach(w => lines.push(`  Week ${w.week} — ${w.focus}:\n${list(w.tasks)}`));
    } else if (key === "plan90Day") {
      const s = section as GrowthReport["plan90Day"];
      s.months?.forEach(m => lines.push(`  Month ${m.month} — ${m.theme}:\n${list(m.milestones)}`));
    } else if (key === "immediateActions") {
      const s = section as GrowthReport["immediateActions"];
      if (s.next24h?.length) lines.push(`Next 24 Hours:\n${list(s.next24h)}`);
      if (s.next72h?.length) lines.push(`Next 72 Hours:\n${list(s.next72h)}`);
    }
  }

  lines.push(`\n${hr}`);
  lines.push(`Powered by Conciply · conciply.com`);
  return lines.join("\n");
}

function WorkspaceContent() {
  const router = useRouter();
  const params = useSearchParams();
  const id = params.get("id") ?? "";

  const [stored, setStored] = useState<StoredReport | null>(null);
  const [tier, setTier] = useState<string | null>(null);
  const [active, setActive] = useState<SectionKey>("executiveSummary");
  const [deepDiveKey, setDeepDiveKey] = useState<SectionKey | null>(null);
  const [regenLoading, setRegenLoading] = useState<SectionKey | null>(null);
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    if (!stored) return;
    navigator.clipboard.writeText(formatReportAsText(stored)).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handlePrint = () => window.print();

  useEffect(() => {
    const plan = getLicensePlan();
    if (!plan) { router.push("/unlock"); return; }
    const r = getReport(id);
    if (!r) { router.push("/"); return; }
    setStored(r);
    setTier(plan);
  }, [id, router]);

  const handleRegenerate = async (key: SectionKey) => {
    if (!stored) return;
    setRegenLoading(key);
    try {
      const licenseKey = getLicenseKey();
      const sectionData = JSON.stringify((stored.report as unknown as Record<string, unknown>)[key] ?? {});
      const res = await fetch("/api/refine", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          ...(licenseKey ? { "x-conciply-license": licenseKey } : {}),
        },
        body: JSON.stringify({ sectionKey: key, input: stored.input, currentContent: sectionData }),
      });
      const data = await res.json();
      if (res.ok && data.section) {
        updateReportSection(stored.id, key, data.section as GrowthReport[typeof key]);
        setStored(getReport(stored.id));
      }
    } finally {
      setRegenLoading(null);
    }
  };

  if (!stored) return null;

  const isPro = tier === "pro" || tier === "agency";
  const isAgency = tier === "agency";

  return (
    <>
      <main className="shell" style={{ paddingTop:32, paddingBottom:80 }}>
        <div style={{ display:"flex", flexWrap:"wrap", alignItems:"center", justifyContent:"space-between",
                      gap:12, borderBottom:"2px solid #F4F4F1", paddingBottom:16, marginBottom:0 }}>
          <div>
            <div className="kicker" style={{ color:"var(--n3)", marginBottom:6 }}>
              {tier} plan · workspace
            </div>
            <h1 className="display" style={{ fontSize:"clamp(20px,3vw,40px)",
                                              whiteSpace:"nowrap", overflow:"hidden", textOverflow:"ellipsis",
                                              maxWidth:"60vw" }}>
              {stored.input}
            </h1>
          </div>
          <div data-print-hide style={{ display:"flex", gap:6 }}>
            <a href={`/report?id=${stored.id}`} className="btn-ghost" style={{ padding:"8px 14px", fontSize:12 }}>
              View Report
            </a>
            <button onClick={handleCopy} className="btn-ghost"
              style={{ padding:"8px 14px", fontSize:12, minWidth:110 }}>
              {copied ? "✓ Copied!" : "Copy Report"}
            </button>
            <button onClick={handlePrint} className="btn-ghost"
              style={{ padding:"8px 14px", fontSize:12 }}>
              Print / PDF
            </button>
            <a href="/" className="btn-neon" style={{ padding:"8px 14px", fontSize:12 }}>
              New Report
            </a>
          </div>
        </div>

        <div style={{ position:"sticky", top:64, zIndex:30, background:"rgba(10,10,11,0.95)",
                      borderBottom:"2px solid #2A2A2E", overflowX:"auto", display:"flex" }}>
          {SECTION_ORDER.map((key, i) => (
            <button key={key} onClick={() => setActive(key)} className="font-mono"
              style={{ flexShrink:0, padding:"12px 16px", fontSize:10, letterSpacing:"0.1em",
                       textTransform:"uppercase", whiteSpace:"nowrap", border:"none",
                       borderBottom: key === active ? "2px solid var(--n1)" : "2px solid transparent",
                       marginBottom:-2, cursor:"pointer",
                       color: key === active ? "var(--n1)" : "#C4C4CC",
                       background:"transparent" }}>
              {String(i+1).padStart(2,"0")} {SECTION_LABELS[key]}
            </button>
          ))}
        </div>

        <div style={{ marginTop:2 }}>
          {regenLoading === active ? (
            <div style={{ padding:"32px 24px" }}>
              <div className="skel" style={{ height:12, width:"40%", marginBottom:12 }} />
              <div className="skel" style={{ height:12, width:"65%", marginBottom:8 }} />
              <div className="skel" style={{ height:12, width:"50%" }} />
              <div className="kicker" style={{ marginTop:20, color:"var(--n1)" }}>Regenerating section…</div>
            </div>
          ) : (
            <SectionCard
              sectionKey={active}
              report={stored.report}
              locked={false}
              onRegenerate={handleRegenerate}
              onDeepDive={isPro ? (key) => setDeepDiveKey(key) : undefined}
            />
          )}
        </div>
      </main>

      {deepDiveKey && stored && (
        <AssetGenerator
          sectionKey={deepDiveKey}
          input={stored.input}
          report={stored.report}
          onClose={() => setDeepDiveKey(null)}
        />
      )}
    </>
  );
}

export default function WorkspacePage() {
  return (
    <>
      <Nav />
      <Suspense>
        <WorkspaceContent />
      </Suspense>
      <Footer />
    </>
  );
}
