"use client";
import { useEffect, useState, Suspense } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Nav, { Footer } from "@/components/Nav";
import SectionCard from "@/components/SectionCard";
import AssetGenerator from "@/components/AssetGenerator";
import { getReport, loadReports, getLicensePlan, getLicenseKey, updateReportSection } from "@/lib/workspace";
import { SECTION_LABELS, FREE_SECTIONS } from "@/lib/types";
import type { StoredReport, SectionKey, GrowthReport } from "@/lib/types";

// ── Shared sidebar config (mirrors ReportView) ────────────────────────────────
const GROUPS: { label: string; color: string; keys: SectionKey[] }[] = [
  { label:"Analysis",  color:"var(--n1)", keys:["executiveSummary","marketAnalysis","competitorAnalysis","positioning"] },
  { label:"Growth",    color:"var(--n3)", keys:["growthOpportunities","acquisitionPlan","funnelImprovements"] },
  { label:"Assets",    color:"var(--n2)", keys:["marketingAssets","salesAssets","retentionStrategy","socialMediaStrategy"] },
  { label:"Execution", color:"#9A9AA8",  keys:["kpiDashboard","topRoiActions","plan7Day","plan30Day","plan90Day","immediateActions"] },
];
const ALL_KEYS: SectionKey[] = GROUPS.flatMap(g => g.keys);
const sectionNum = (key: SectionKey) => String(ALL_KEYS.indexOf(key) + 1).padStart(2, "0");

const ICONS: Record<SectionKey, string> = {
  executiveSummary:"◈", marketAnalysis:"◎", competitorAnalysis:"⊕", positioning:"◆",
  growthOpportunities:"▲", acquisitionPlan:"➤", funnelImprovements:"◑",
  marketingAssets:"✦", salesAssets:"◉", retentionStrategy:"⟳", socialMediaStrategy:"◈",
  kpiDashboard:"▣", topRoiActions:"★", plan7Day:"①", plan30Day:"②", plan90Day:"③", immediateActions:"⚡",
};

const SECTION_SUBTITLES: Partial<Record<SectionKey, string>> = {
  executiveSummary:    "Your ICP, unique value proposition, and single biggest opportunity at a glance.",
  marketAnalysis:      "TAM / SAM / SOM sizing and the market trends that matter most for your growth.",
  competitorAnalysis:  "Who you're up against, where they're weak, and the gaps you can exploit.",
  positioning:         "How to frame your brand so the right customers immediately get it.",
  growthOpportunities: "Organic, paid, product-led, and viral levers ranked by potential impact.",
  acquisitionPlan:     "Which channels to prioritise, exact tactics, and how to split your budget.",
  funnelImprovements:  "Where you're leaking revenue and how to fix each stage of the funnel.",
  marketingAssets:     "Ready-to-use landing copy, ad headlines, and a full email sequence.",
  salesAssets:         "Cold outreach script, discovery questions, and objection-handling playbook.",
  retentionStrategy:   "Onboarding steps, engagement loops, and upsell moments to reduce churn.",
  socialMediaStrategy: "Platform-by-platform playbooks, post ideas, hooks, and a 4-week content calendar.",
  kpiDashboard:        "The metrics you must track, your 90-day targets, and red flags to watch.",
  topRoiActions:       "Your highest-leverage moves ranked by impact, speed, and ease — do these first.",
  plan7Day:            "Day-by-day sprint to get the most critical foundations in place this week.",
  plan30Day:           "Week-by-week execution plan to build momentum and hit your first milestone.",
  plan90Day:           "Three-month roadmap from launch to traction — themes, milestones, and metrics.",
  immediateActions:    "What to do in the next 24 and 72 hours to start moving right now.",
};

// ── Plain-text export helper ──────────────────────────────────────────────────
function formatReportAsText(stored: StoredReport): string {
  const r = stored.report as unknown as Record<string, unknown>;
  const lines: string[] = [];
  const hr = "─".repeat(60);
  lines.push(`GROWTH PLAYBOOK: ${stored.input.toUpperCase()}`);
  lines.push(`Generated by Conciply · ${new Date(stored.createdAt).toLocaleDateString()}`);
  lines.push(hr);
  const list = (arr: unknown[]) => arr.map(s => `  • ${s}`).join("\n");
  for (const key of ALL_KEYS) {
    const section = r[key];
    if (!section) continue;
    lines.push(`\n${SECTION_LABELS[key as SectionKey].toUpperCase()}`);
    lines.push(hr);
    if (key === "executiveSummary") {
      const s = section as GrowthReport["executiveSummary"];
      lines.push(`ICP: ${s.icp}\nUVP: ${s.uvp}\nTop Opportunity: ${s.topOpportunity}`);
      if (s.assumptions?.length) lines.push(`Assumptions:\n${list(s.assumptions)}`);
    } else if (key === "topRoiActions") {
      const s = section as GrowthReport["topRoiActions"];
      s.actions?.forEach((a, i) => lines.push(`  ${i+1}. ${a.title} (Score: ${a.score})\n     ${a.description}`));
    } else {
      lines.push(JSON.stringify(section, null, 2));
    }
  }
  lines.push(`\n${hr}\nPowered by Conciply · conciply.com`);
  return lines.join("\n");
}

// ── Main workspace component ──────────────────────────────────────────────────
function WorkspaceContent() {
  const router = useRouter();
  const params = useSearchParams();
  const id = params.get("id") ?? "";

  const [stored, setStored]           = useState<StoredReport | null>(null);
  const [tier, setTier]               = useState<string | null>(null);
  const [active, setActive]           = useState<SectionKey>("executiveSummary");
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [historyOpen, setHistoryOpen] = useState(false);
  const [allReports, setAllReports]   = useState<StoredReport[]>([]);
  const [deepDiveKey, setDeepDiveKey] = useState<SectionKey | null>(null);
  const [copied, setCopied]           = useState(false);
  const [billingLoading, setBillingLoading] = useState(false);
  const [billingError, setBillingError] = useState("");

  useEffect(() => {
    const plan = getLicensePlan();
    if (!plan) { router.push("/unlock"); return; }
    const reports = loadReports().reverse(); // newest first
    setAllReports(reports);
    setTier(plan);
    const r = getReport(id);
    if (!r) {
      // No specific report selected — redirect to the most recent one if available
      if (reports.length > 0) {
        router.replace(`/workspace?id=${reports[0].id}`);
      } else {
        router.push("/"); // No reports at all — go generate one
      }
      return;
    }
    setStored(r);
  }, [id, router]);


  const handleCopy = () => {
    if (!stored) return;
    navigator.clipboard.writeText(formatReportAsText(stored)).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }).catch(() => {
      // Clipboard API unavailable (non-HTTPS or permission denied) — silent fail
    });
  };

  const handleBilling = async () => {
    setBillingLoading(true);
    try {
      const key = getLicenseKey();
      const res = await fetch("/api/billing-portal", {
        method: "POST",
        headers: { ...(key ? { "x-conciply-license": key } : {}) },
      });
      const data = await res.json();
      if (data.url) window.location.href = data.url;
      else { setBillingError(data.error || "Could not open billing portal."); setTimeout(() => setBillingError(""), 4000); }
    } finally {
      setBillingLoading(false);
    }
  };


  if (!stored) return null;

  const isPaid      = !!tier;
  const canDeepDive = tier === "pro" || tier === "agency";
  const activeGroup = GROUPS.find(g => g.keys.includes(active))!;

  return (
    <>
      <div style={{ display:"flex", minHeight:"calc(100vh - 64px)", position:"relative" }}>

        {/* Mobile toggle */}
        <button onClick={() => setSidebarOpen(o => !o)} className="font-mono"
          aria-label={sidebarOpen ? "Close workspace menu" : "Open workspace menu"}
          style={{ display:"none", position:"fixed", bottom:24, right:24, zIndex:50,
                   background:"var(--n2)", color:"#000", border:"none", padding:"12px 18px",
                   fontSize:14, letterSpacing:"0.1em", cursor:"pointer" }}
          data-ws-toggle>
          {sidebarOpen ? "✕ Close" : "☰ Sections"}
        </button>

        {/* Mobile backdrop — tap to close sidebar */}
        {sidebarOpen && (
          <div onClick={() => setSidebarOpen(false)}
            style={{ display:"none", position:"fixed", inset:0, zIndex:39,
                     background:"rgba(0,0,0,0.55)" }}
            data-ws-backdrop />
        )}

        {/* ── Left sidebar ──────────────────────────────────────────────── */}
        <aside data-ws-sidebar={sidebarOpen ? "open" : "closed"} style={{
          width:260, flexShrink:0, borderRight:"2px solid #1E1E22",
          position:"sticky", top:64, height:"calc(100vh - 64px)",
          overflow:"hidden", display:"flex", flexDirection:"column",
          background:"#0A0A0B",
        }}>
          {/* Report title + tier badge */}
          <div style={{ padding:"20px 16px 16px", borderBottom:"1px solid #1E1E22" }}>
            <div style={{ fontSize:12, fontFamily:"var(--font-mono)", letterSpacing:"0.12em",
                          color:"#5C5C63", textTransform:"uppercase", marginBottom:6 }}>
              Workspace
            </div>
            <div style={{ fontSize:18, fontWeight:700, color:"#F4F4F1", lineHeight:1.4,
                          display:"-webkit-box", WebkitLineClamp:2, WebkitBoxOrient:"vertical",
                          overflow:"hidden", marginBottom:10 }}>
              {stored.input}
            </div>
            <span style={{ fontSize:12, fontFamily:"var(--font-mono)", fontWeight:700,
                           letterSpacing:"0.1em", textTransform:"uppercase",
                           color:"#000", background:"var(--n2)", padding:"3px 8px" }}>
              {tier} · editing
            </span>
          </div>

          {/* Privacy notice */}
          <div style={{ padding:"10px 16px", borderBottom:"1px solid #1E1E22",
                        background:"#0D0D10" }}>
            <div style={{ display:"flex", gap:8, alignItems:"flex-start" }}>
              <span style={{ fontSize:14, color:"#3C3C42", flexShrink:0, marginTop:1 }}>🔒</span>
              <p style={{ margin:0, fontSize:12, fontFamily:"var(--font-mono)",
                          color:"#7A7A88", letterSpacing:"0.03em", lineHeight:1.6 }}>
                Your reports are stored <span style={{ color:"#B0B0BC" }}>only in this browser</span> — we collect no data.
                History is lost if you clear your browser, switch browsers, or use a different device.
                Up to 20 reports saved locally.
              </p>
            </div>
          </div>

          {/* Report history — collapsible */}
          {allReports.length > 1 && (
            <div style={{ borderBottom:"1px solid #1E1E22" }}>
              <button
                onClick={() => setHistoryOpen(o => !o)}
                style={{ width:"100%", background:"transparent", border:"none", cursor:"pointer",
                         padding:"10px 16px", display:"flex", alignItems:"center",
                         justifyContent:"space-between", gap:8 }}>
                <span style={{ fontSize:11, fontFamily:"var(--font-mono)", fontWeight:700,
                               letterSpacing:"0.14em", textTransform:"uppercase", color:"#5C5C63" }}>
                  Recent Reports
                </span>
                <span style={{ fontSize:12, color:"#3C3C42" }}>{historyOpen ? "▲" : "▼"}</span>
              </button>
              {historyOpen && (
                <div style={{ maxHeight:200, overflowY:"auto", paddingBottom:8 }}>
                  {allReports.map(r => {
                    const isCurrent = r.id === stored.id;
                    return (
                      <button key={r.id}
                        onClick={() => { router.push(`/workspace?id=${r.id}`); setHistoryOpen(false); }}
                        style={{ width:"100%", textAlign:"left", border:"none", cursor:"pointer",
                                 padding:"8px 16px", background: isCurrent ? "#16161A" : "transparent",
                                 borderLeft: isCurrent ? "2px solid #5C5C63" : "2px solid transparent" }}>
                        <div style={{ fontSize:13, fontWeight:600, color: isCurrent ? "#F4F4F1" : "#9A9AA8",
                                      lineHeight:1.3, fontFamily:"var(--font-archivo), sans-serif",
                                      display:"-webkit-box", WebkitLineClamp:2,
                                      WebkitBoxOrient:"vertical", overflow:"hidden" }}>
                          {r.input}
                        </div>
                        <div style={{ fontSize:11, fontFamily:"var(--font-mono)", color:"#3C3C42",
                                      letterSpacing:"0.06em", marginTop:3 }}>
                          {new Date(r.createdAt).toLocaleDateString(undefined, { month:"short", day:"numeric", year:"numeric" })}
                        </div>
                      </button>
                    );
                  })}
                </div>
              )}
            </div>
          )}

          {/* Section nav — scrollable middle */}
          <nav style={{ flex:1, overflowY:"auto", padding:"8px 0" }}>
            {GROUPS.map(group => (
              <div key={group.label} style={{ marginBottom:4 }}>
                <div style={{ padding:"10px 16px 6px", fontSize:11, fontFamily:"var(--font-mono)",
                              fontWeight:700, letterSpacing:"0.14em", textTransform:"uppercase",
                              color: group.color }}>
                  {group.label}
                </div>
                {group.keys.map(key => {
                  const isActive = key === active;
                  return (
                    <button key={key} onClick={() => { setActive(key); setSidebarOpen(false); }}
                      style={{ width:"100%", textAlign:"left", border:"none", cursor:"pointer",
                               padding:"9px 16px", display:"flex", alignItems:"center", gap:10,
                               background: isActive ? "#16161A" : "transparent",
                               borderLeft: isActive ? `2px solid ${group.color}` : "2px solid transparent",
                               transition:"background 0.1s" }}>
                      <span style={{ fontSize:11, fontFamily:"var(--font-mono)",
                                     color: isActive ? group.color : "#3C3C42", flexShrink:0, width:18 }}>
                        {sectionNum(key)}
                      </span>
                      <span style={{ fontSize:16, color: isActive ? group.color : "#5C5C63", flexShrink:0 }}>
                        {ICONS[key]}
                      </span>
                      <span style={{ fontSize:14, fontFamily:"var(--font-mono)", letterSpacing:"0.04em",
                                     color: isActive ? "#F4F4F1" : "#9A9AA8", lineHeight:1.3 }}>
                        {SECTION_LABELS[key]}
                      </span>
                    </button>
                  );
                })}
              </div>
            ))}
          </nav>

          {/* ── Export panel — pinned to sidebar bottom ── */}
          <div style={{ borderTop:"1px solid #1E1E22", padding:"12px 16px", background:"#0A0A0B" }}>
            <div style={{ fontSize:11, fontFamily:"var(--font-mono)", fontWeight:700,
                          letterSpacing:"0.14em", textTransform:"uppercase",
                          color:"#3C3C42", marginBottom:10 }}>
              Export
            </div>
            <div style={{ display:"flex", flexDirection:"column", gap:6 }}>
              <button onClick={handleCopy}
                style={{ width:"100%", textAlign:"left", background:"transparent",
                         border:"1px solid #2A2A2E", color: copied ? "var(--n3)" : "#9A9AA8",
                         borderColor: copied ? "var(--n3)" : "#2A2A2E",
                         padding:"8px 12px", cursor:"pointer",
                         fontFamily:"var(--font-mono)", fontSize:13,
                         letterSpacing:"0.06em", display:"flex", alignItems:"center", gap:8 }}>
                <span style={{ flexShrink:0 }}>⎘</span>
                {copied ? "Copied to clipboard!" : "Copy plain text"}
              </button>
              <a href={`/report?id=${stored.id}`} target="_blank" rel="noopener noreferrer"
                style={{ width:"100%", textAlign:"left", background:"transparent",
                         border:"1px solid #2A2A2E", color:"#9A9AA8",
                         padding:"8px 12px", cursor:"pointer",
                         fontFamily:"var(--font-mono)", fontSize:13,
                         letterSpacing:"0.06em", display:"flex", alignItems:"center", gap:8,
                         textDecoration:"none" }}>
                <span style={{ flexShrink:0 }}>⎙</span>
                Print / Save PDF
              </a>
              <a href="/" style={{ width:"100%", textAlign:"left", background:"transparent",
                         border:"1px solid #2A2A2E", color:"#9A9AA8",
                         padding:"8px 12px", cursor:"pointer",
                         fontFamily:"var(--font-mono)", fontSize:13,
                         letterSpacing:"0.06em", display:"flex", alignItems:"center", gap:8,
                         textDecoration:"none" }}>
                <span style={{ flexShrink:0 }}>⊕</span>
                New report
              </a>
              <button onClick={handleBilling} disabled={billingLoading}
                title={billingError || undefined}
                style={{ width:"100%", textAlign:"left", background:"transparent",
                         border:"1px solid #2A2A2E",
                         color: billingError ? "var(--n2)" : "#5C5C63",
                         borderColor: billingError ? "var(--n2)" : "#1E1E22",
                         padding:"8px 12px", cursor: billingLoading ? "wait" : "pointer",
                         fontFamily:"var(--font-mono)", fontSize:13,
                         letterSpacing:"0.06em", display:"flex", alignItems:"center", gap:8 }}>
                <span style={{ flexShrink:0 }}>⚙</span>
                {billingLoading ? "Opening…" : billingError ? "⚠ Billing error" : "Billing"}
              </button>
            </div>
          </div>

        </aside>

        {/* ── Right content panel ──────────────────────────────────────── */}
        <main style={{ flex:1, minWidth:0, display:"flex", flexDirection:"column" }}>

          {/* ── Sticky toolbar: breadcrumb + global actions + section actions ── */}
          <div style={{
            position:"sticky", top:64, zIndex:20,
            background:"rgba(10,10,11,0.97)", backdropFilter:"blur(8px)",
            borderBottom:"1px solid #1E1E22",
            padding:"0 24px",
            display:"flex", alignItems:"center", justifyContent:"space-between",
            gap:12, height:48, flexWrap:"nowrap", overflowX:"auto",
          }}>
            {/* Breadcrumb — left */}
            <div style={{ display:"flex", alignItems:"center", gap:8, flexShrink:0 }}>
              <span style={{ fontSize:12, fontFamily:"var(--font-mono)", color:activeGroup.color,
                             letterSpacing:"0.12em", textTransform:"uppercase" }}>
                {activeGroup.label}
              </span>
              <span style={{ color:"#2A2A2E" }}>›</span>
              <span style={{ fontSize:13, fontFamily:"var(--font-mono)", color:"#F4F4F1",
                             letterSpacing:"0.06em", whiteSpace:"nowrap" }}>
                {SECTION_LABELS[active]}
              </span>
            </div>

            {/* Section actions — right */}
            <div style={{ display:"flex", alignItems:"center", gap:4, flexShrink:0 }}>
              {canDeepDive ? (
                <button onClick={() => setDeepDiveKey(active)} className="btn-ghost"
                  style={{ padding:"5px 10px", fontSize:12, letterSpacing:"0.08em", whiteSpace:"nowrap",
                           color:"var(--n2)", borderColor:"var(--n2)" }}>
                  ⚡ Deep Dive
                </button>
              ) : isPaid && (
                <a href="/pricing" className="btn-ghost"
                  style={{ padding:"5px 10px", fontSize:12, letterSpacing:"0.08em", whiteSpace:"nowrap",
                           color:"#5C5C63", borderColor:"#3C3C42", textDecoration:"none" }}
                  title="Deep Dive is available on Pro and Agency plans">
                  ⚡ Deep Dive ↑
                </a>
              )}
              {/* Counter */}
              <span style={{ fontSize:12, fontFamily:"var(--font-mono)", color:"#5C5C63",
                             letterSpacing:"0.1em", marginLeft:8, flexShrink:0 }}>
                {sectionNum(active)} / {ALL_KEYS.length}
              </span>
            </div>
          </div>

          {/* Section content */}
          <div style={{ padding:"32px 40px", flex:1 }}>

            {/* Big section title */}
            <div style={{ marginBottom:32, paddingBottom:24, borderBottom:`2px solid ${activeGroup.color}` }}>
              <div style={{ fontSize:13, fontFamily:"var(--font-mono)", letterSpacing:"0.14em",
                            textTransform:"uppercase", color: activeGroup.color, marginBottom:10 }}>
                {sectionNum(active)} — {activeGroup.label}
              </div>
              <h2 className="display" style={{ fontSize:"clamp(32px, 3.5vw, 56px)",
                                               fontWeight:900, color:"#F4F4F1", lineHeight:1.05,
                                               margin:0, letterSpacing:"-0.02em" }}>
                {SECTION_LABELS[active]}
              </h2>
              {SECTION_SUBTITLES[active] && (
                <p style={{ margin:"12px 0 0", fontSize:16, color:"#9A9AA8",
                            lineHeight:1.5, fontFamily:"var(--font-grotesk), sans-serif" }}>
                  {SECTION_SUBTITLES[active]}
                </p>
              )}
            </div>

            <SectionCard
              sectionKey={active}
              report={stored.report}
              locked={false}
            />

            {/* ── Email capture banner ─────────────────────────────── */}
            {/* Prev / Next navigation */}
            <div style={{ display:"flex", justifyContent:"space-between", marginTop:24, gap:12 }}>
              {(() => {
                const idx  = ALL_KEYS.indexOf(active);
                const prev = idx > 0 ? ALL_KEYS[idx - 1] : null;
                const next = idx < ALL_KEYS.length - 1 ? ALL_KEYS[idx + 1] : null;
                return (
                  <>
                    <button onClick={() => prev && setActive(prev)} disabled={!prev}
                      className="btn-ghost" style={{ padding:"10px 18px", fontSize:14,
                      opacity: prev ? 1 : 0.2, cursor: prev ? "pointer" : "default" }}>
                      ← {prev ? SECTION_LABELS[prev] : ""}
                    </button>
                    <button onClick={() => next && setActive(next)} disabled={!next}
                      className="btn-ghost" style={{ padding:"10px 18px", fontSize:14,
                      opacity: next ? 1 : 0.2, cursor: next ? "pointer" : "default",
                      borderColor: next ? activeGroup.color : undefined,
                      color: next ? activeGroup.color : undefined }}>
                      {next ? SECTION_LABELS[next] : ""} →
                    </button>
                  </>
                );
              })()}
            </div>
          </div>
        </main>

        <style>{`
          @media (max-width: 768px) {
            [data-ws-toggle] { display: block !important; }
            [data-ws-sidebar] {
              position: fixed !important;
              top: 64px !important;
              left: 0 !important;
              height: calc(100vh - 64px) !important;
              z-index: 40;
              transform: translateX(-100%);
              transition: transform 0.2s ease;
              box-shadow: 4px 0 24px rgba(0,0,0,0.6);
            }
            [data-ws-sidebar="open"] {
              transform: translateX(0) !important;
            }
          }
          @media print {
            /* Hide everything except the print container */
            body > * { display: none !important; }
            #print-report { display: block !important; }
          }
        `}</style>
      </div>

      {/* ── Hidden print container — renders ALL sections for Print / PDF ── */}
      <div id="print-report" style={{ display:"none" }}>
        <div style={{ fontFamily:"system-ui, sans-serif", padding:"24px 32px", maxWidth:900, margin:"0 auto" }}>
          {/* Cover */}
          <div style={{ borderBottom:"3px solid #000", paddingBottom:16, marginBottom:32 }}>
            <div style={{ fontSize:13, letterSpacing:"0.12em", textTransform:"uppercase",
                          color:"#666", marginBottom:6, fontFamily:"monospace" }}>
              Conciply Growth Playbook
            </div>
            <h1 style={{ fontSize:34, fontWeight:900, margin:"0 0 8px", lineHeight:1.1 }}>
              {stored.input}
            </h1>
            <div style={{ fontSize:14, color:"#666", fontFamily:"monospace" }}>
              {tier?.toUpperCase()} PLAN · Generated {new Date(stored.createdAt).toLocaleDateString("en-GB", { day:"numeric", month:"long", year:"numeric" })} · conciply.com
            </div>
          </div>

          {/* All sections */}
          {ALL_KEYS.map((key, i) => {
            const group = GROUPS.find(g => g.keys.includes(key))!;
            return (
              <div key={key} style={{ marginBottom:40, pageBreakInside:"avoid" }}>
                <div style={{ display:"flex", alignItems:"baseline", gap:10, borderBottom:"1px solid #ddd",
                              paddingBottom:8, marginBottom:16 }}>
                  <span style={{ fontSize:12, fontFamily:"monospace", color:"#999",
                                 letterSpacing:"0.1em", textTransform:"uppercase" }}>
                    {String(i+1).padStart(2,"0")} — {group.label}
                  </span>
                  <h2 style={{ fontSize:22, fontWeight:800, margin:0, textTransform:"uppercase",
                               letterSpacing:"-0.01em" }}>
                    {SECTION_LABELS[key]}
                  </h2>
                </div>
                <SectionCard sectionKey={key} report={stored.report} locked={false} />
              </div>
            );
          })}

          <div style={{ borderTop:"2px solid #000", paddingTop:12, marginTop:40,
                        fontSize:13, color:"#999", fontFamily:"monospace", textAlign:"center" }}>
            Powered by Conciply · conciply.com · AI-generated for strategic inspiration
          </div>
        </div>
      </div>

      {deepDiveKey && stored && (
        <AssetGenerator
          sectionKey={deepDiveKey}
          input={stored.input}
          report={stored.report}
          onClose={() => setDeepDiveKey(null)}
        />
      )}
    </>
  );
}

export default function WorkspacePage() {
  return (
    <>
      <Nav />
      <Suspense>
        <WorkspaceContent />
      </Suspense>
      <Footer />
    </>
  );
}
